# Generated by Django 3.2 on 2022-02-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbookshelf2022', '0002_auto_20220216_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='book_image',
        ),
    ]
