# Generated by Django 3.2 on 2022-02-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbookshelf2022', '0004_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
    ]
