# Generated by Django 3.2 on 2022-02-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbookshelf2022', '0005_remove_post_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='book_image',
            new_name='featured_image',
        ),
        migrations.AddField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
