# Generated by Django 3.2 on 2022-02-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbookshelf2022', '0008_auto_20220216_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image_cloud',
        ),
        migrations.AddField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
