# Generated by Django 3.2 on 2022-02-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbookshelf2022', '0011_auto_20220216_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='my@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Mary', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Ann', max_length=255),
        ),
    ]
