# Generated by Django 3.2 on 2022-02-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbookshelf2022', '0016_alter_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
